-- =============================================================================
-- Portfelik — Seed Data
-- Run via: supabase db seed (local) or applied to staging by CI.
--
-- Default transaction categories are NO LONGER global rows. As of migration
-- 20260605000000_categories_per_user.sql every user owns their own copy of the
-- default set, seeded automatically by the `seed_default_categories_after_profile_insert`
-- trigger when their profile row is created (i.e. on signup / persona seeding).
--
-- There is therefore nothing for the system seed to insert here. Persona and
-- demo data are created separately by scripts/seed-personas.mjs (local/staging)
-- and scripts/seed-staging.mjs (synthetic staging fixtures).
-- =============================================================================
